'use strict';
var app = angular.module('gameApp',['ngRoute', 'ngSanitize', 'ngAnimate','ksSwiper','ngDialog', 'ngNotify', 'pascalprecht.translate', 'ngCookies', 'timer', 'ui.grid', 'ui.grid.edit', 'ui.grid.pagination']);

app.config(['$routeProvider', function ($routeProvider) {
	$routeProvider
		.when('/',{
			templateUrl:'/templates/main.html',
			controller:'homeCtrl'
		})
		.when('/top',{
			templateUrl:'/templates/top.html',
			controller:'topCtrl'
		})
		.when('/history',{
			templateUrl:'/templates/history.html',
			controller:'historyCtrl'
		})
		.when('/try',{
			templateUrl:'/templates/try.html',
			controller:'tryCtrl'
		})
		.when('/about',{
			templateUrl:'/templates/about.html',
			controller:'aboutCtrl'
		}) 
		.when('/roulettepage',{
			templateUrl:'/templates/roulettepage.html',
			controller:'roulettepageCtrl'
		}) 
		.when('/double',{
			templateUrl:'/templates/double.html',
			controller:'doubleCtrl'
		}) 
		.when('/raffles',{
			templateUrl:'/templates/raffles.html',
			controller:'rafflesCtrl'
		}) 
		.when('/shop',{
			templateUrl:'/templates/shop.html',
			controller:'shopCtrl'
		})  
		.when('/raffles/item',{
			templateUrl:'/templates/raffles-item.html',
			controller:'raffles-itemCtrl'
		})   
		.when('/invites', {
			templateUrl : '/templates/pages/invites.html',
			controller : 'invitesCtrl'
		})
		.when('/support', {
			templateUrl : '/templates/support.html',
			controller : 'supportCtrl'
		})
		.when('/game/:gameId', {
			templateUrl:'/templates/game.html',
			controller : 'gameCtrl'
		})
		.when('/fairplay', {
			templateUrl:'/templates/fair-play.html',
			controller : 'fairplayCtrl'
		})
		.when('/my/profile', {
			templateUrl : '/templates/my-profile.html',
			controller : 'myProfileCtrl'
		})
		.when('/my/history', {
			templateUrl : '/templates/my-history.html',
			controller : 'myHistoryCtrl'
		})
		.when('/my/inventory', {
			templateUrl : '/templates/my-inventory.html',
			controller : 'myInventoryCtrl'
		})
		.when('/admin', {
			templateUrl : '/templates/admin.html',
			controller : 'adminCtrl'
		})
		.when('/admin/admins', {
			templateUrl : '/templates/admin-admins.html',
			controller : 'adminAdminsCtrl'
		})
		.when('/admin/banned', {
			templateUrl : '/templates/admin-banned.html',
			controller : 'adminBannedCtrl'
		})
		.when('/admin/items', {
			templateUrl : '/templates/admin-items.html',
			controller : 'adminItemsCtrl'
		})
		.when('/double', {
			templateUrl : '/templates/double.html',
			controller : 'doubleCtrl'
		})
		.otherwise({
			redirectTo : '/'
		})
}]);

app.config(['$translateProvider', function ($translateProvider) {
  $translateProvider.translations('en', {
	'LOGO' : '/img/logo-en.png',
	'MENU_MAIN': 'Home',
	'MENU_PLAY': 'Play',
	'MENU_ABOUT': 'About',
	'MENU_TOP': 'TOP players',
	'MENU_HISTORY': 'History',
	'MENU_INVENTORY': 'Inventory',
	'MENU_PROFILE': 'Profile',
	'MENU_LOGOUT': 'Logout',
	'MENU_SUPPORT': 'Support',
	'LOGIN_VIA_STEAM' : 'Log in via Steam',
	'FOOTER_POWERED' : 'Powered by Steam, a registered trademark of Valve Corporation.',
	'SIDEBAR_ADD_TO_NICK_TITLE' : 'Add "STEAMWIN.COM" to your Steam nickname and get <span>bonus</span> <span>+5%</span> to your prize ',
	'SIDEBAR_ADD_TO_NICK_DESCR' : 'After nickname change, click "Logout" and then relogin via steam.',
	'SIDEBAR_LAST_WINNER' : 'Last winner:',
	'SIDEBAR_LAST_WINNER_MONEY' : 'Winning:',
	'SIDEBAR_LAST_WINNER_CHANCE' : 'Chance:',
	'SIDEBAR_ONLINE' : 'Online now',
	'SIDEBAR_PRICES' : 'Prices are presented:',
	'MAIN_JACKPOT_TITLE' : 'MAIN GAME JACKPOT:',
	'MAIN_JACKPOT_DESCR' : 'Players make bets and when maximum item limit is reached, service randomly choose the winner who gets all skins. The larger bet - the bigger chance to win.',
	'MAIN_INFORMERS_GAMES_TODAY' : 'Today games',
	'MAIN_INFORMERS_PLAYERS_TODAY' : 'Today unique players',
	'MAIN_INFORMERS_ITEMS_TODAY' : 'Today items count',
	'MAIN_INFORMERS_MAX_JACKPOT' : 'Maximum jackpot',
	'MAIN_BANNER_TITLE' : 'Take part in prize drawing!<br>Join us in VK and take your knife!',
	'MAIN_BANNER_BUTTON' : 'Get knife',
	'GAME_NUMBER' : 'Game',
	'SOUND_ON' : 'Turn sound on',
	'SOUND_OFF' : 'Turn sound off',
	'BEFORE_TIMER_TEXT' : 'till the prize drawing',
	'ITEMS' : 'items',
	'OR_AFTER' : 'or after',
	'ENTER_GAME_AND_WIN' : 'Join the game and win',
	'YOU_BET' : 'You put',
	'MIN_DEPOSITE' : 'Min.deposite',
	'MAX_ITEMS' : 'Items limit',
	'GAME_ADDITIONAL_TEXT' : 'The larger bet - the bigger prize!',
	'MORE' : 'More',
	'YOUR_CHANCE' : 'Your chance',
	'GAME_STARTED_FIRST' : 'Game started! Make bet first!',
	'GAME_STARTED' : 'Game started! Make bets!',  
	'TOP_GAMERS' : 'Top players',
	'GAMERS_IN_RAITING' : 'Players <br>in raiting',
	'MAX_TODAY_WIN' : 'Maximum <br>jackpot today',
	'TOP_PLACE' : 'Place',
	'TOP_RANK'  : 'Rank',
	'STEAM_NICK' : 'Steam nickname',
	'WIN_COUNT' : 'Win count',
	'WON' : 'Won',
	'ALL_GAMES' : 'All games',
	'CHANCE' : 'Chance',
	'IN_GAME' : 'STAKE IS',
	'ENTER_AND_PLAY' : 'Login and game',
	'PLAYER_WON' : 'Player won',
	'FROM' : 'from',
	'CHOOSE_GAME' : 'Chose room',
	'ENTER_LINK' : 'Attantion! You should enter trade link. ',
	'WHERE_LINK' : 'Where can I get link?',
	'FOR_EXAMPLE' : 'For example',
	'SAVE_LINK' : 'Save link',
	'FOR_SURE' : 'For sure',
	'OPEN_INVENTORY' : 'open inventory',
	'TO_TAKE_PRIZE' : 'in Steam to take prize',
	'ADD_MORE_ITEMS' : 'Bet more',
	'END_GAME' : 'Game ended! Bot takes last bets..',
	'PUTTED' : 'put',
	'END_GAME_STATUS' : 'Game Ended!',
	'ENTER_TRADELINK' : 'Enter trade-offer link',
	'ONLINE' : 'online',
	'TODAY_GAMES' : 'games today',
	'TODAY_GAMERS' : 'gamers today',
	'MAXIMUM_JACKPOT' : 'maximum jackpot',
	'TODAYS_WON' : 'today won',
	'SHOW_MAIN_BANNER' : 'display:none;',
	'GAME' : 'GAME',
	'BANK' : 'BANK',
	'GAME_START' : 'Game start',
	'TICKETS' : 'Tickets',
	'FROMTO' : 'from',
	'TO' : 'till',
	'HASH' : 'hash',
	'ROUND' : 'round',
	'MAIN_MENU_SUPPORT': 'Support',
	'TODAY_WIN': 'today win',
	'OR_TEXT': 'or in',
	'YOUR_BANK': 'Your bank',
	'OF': 'of',
	'YOUR_CHANCE_2': 'Your chance to win',
	'ADD_ITEMS': 'Add items',
	'ADD': 'Add',
	'ADD_CSGOIN': 'to nickname csgo.in and get +5% to winning',
	'TAKE': 'Dear winners! To avoid problems we ask',
	'MAX':'MAX',
	'TAKE_0': 'immediately',
	'TAKE_0_1': 'TAKE',
	'TEXT_0': 'Your prize!',
	'TEXT_1': 'ATTENTION! Minimum deposit',
	'TEXT_2': 'Maximum deposit -',
	'TEXT_3': 'items. To start 2 players needed.',
	'TEXT_4': 'The game is complete! Accept recent deposits.',	
	'TEXT_5': 'Fair game',													
	'TEXT_6': 'Secret number of round:',
	'TEXT_7': 'Winning ticket:',
	'TEXT_7_1': 'winning ticket:',
	'TEXT_8': 'contributed',
	'TEXT_9': 'items',
	'TEXT_10': 'The game has begun! Make a deposit!',
	'TEXT_12': 'Hash of round:',
	'TEXT_13': '- Service involving bring their items ( skins ) and when the sum recruited 100 subjects , or expires , the system determines one winner, and that gets all contributed items.',
	'TEXT_14': 'The winner is determined by random chance of winning depends on the cost made skins.',
	'TEXT_15': 'THE PRINCIPLE IS SIMPLE',
	'TEXT_16': 'THE LARGER AND MORE EXPENSIVE ITEMS YOU BET , THE GREATER THE CHANCE TO HIT',
	'TEXT_17': 'THE JACKPOT ! BUT EVEN PUTTING ONE PENNY , YOU HAVE THE OPPORTUNITY TO HIT THE JACKPOT!',
	'TEXT_18': 'HOW IT WORKS?',
	'TEXT_19': 'You pay your items through the " Participate " , sending our trade bot.',
	'TEXT_20': 'You can enter a maximum of 16 skins at a time , the total of which may not be less than 30 rub',
	'TEXT_21': 'We translate the changes you items Points In accordance with their price .',
	'TEXT_22': 'For every 1 cent of the cost of the items you will get 1 point ( $ 1 - 100 points ) . Chance to win it depends on the number of points. The more objects you make - the more your chance to win.',
	'TEXT_23': 'When the threshold of 100 skins , or after the time we collect all points issued together and randomly choose one winner .',
	'TEXT_24': 'By the way, those gamers who have more points than other gamers take precedence.',
	'TEXT_25': 'The winner gets ALL items with the commission in the end of the round.',
	'TEXT_26': 'RULES AND FEATURES:',
	'TEXT_27': 'Maximum deposit items - 16 pieces for one trade. There are no upper limits to the price, but deposit may begin with a total amount of the items at least 30 rub.',
	'TEXT_28': 'If any items give in the “Bank” at last deposit and counter of objects passed a certain amount, items will be counting in this game, because the user made their participation in current but not in the previous round.',
	'TEXT_29': 'We take commission for developing and making competitions on the site- 10% from all items of the each game.',
	'TEXT_30': 'Deposits and withdrawal of the prize almost instantly. Acceptance for 7 seconds. Withdrawal immediately.',
	'TEXT_31': 'Every time when you’re sending items, you agree to the terms of use of the site.',
	'TEXT_32': 'If your inventory is closed, the next and the last try to send the prize will be after 1 hour. Resending of the prize will make by the technical support.',
	'TEXT_33': 'System can take items just for CS:GO, other items will be taken, but wouldn’t be counted on the website. Also we can guarantee the right counting of the value of items only if Steam market has them or items haven’t the highest (ten times higher) last sale. Because of this two reasons your items can be counted incorrectly.',
	'TEXT_34': 'Forbidden to put gift items and gift sets. These trades will be cancelled.',
	'TEXT_34_1': 'And accept only those items that are on ',
	'TEXT_34_2': 'Steam market has them',
	'TEXT_35': 'You have the guarantee for take your items until 23:00 of the same day. After this time we are not responsible for lost items.',
	'TEXT_36': 'If you cancel the exchange or sent a contra-proposal after the winning, your items wouldn’t return to you because the bot cannot re-post things.',
	'TEXT_37': 'If our bot banned for 30 minutes after the end of the match, we will refund your bet, but not the prize.',
	'TEXT_38': 'If you bet for 30 seconds before the end of the match, you have a possibility that your skins will go to the next game. We are not responsible for this: sometimes steam makes this a little bit slowly.',
	'TEXT_39': 'If for some reason the game was stopped (Steam off), or you haven’t any game, we will refund just your deposit via support.',
	'TEXT_40': 'Game Ended',
	'TEXT_41': 'BACK TO HOME PAGE',
	'TEXT_43': '(number of the round)',
	'TEXT_44': '(bank in cents)',
	'TEXT_45': '(course $)',
	'TEXT_46': '(winning ticket)',
	'TEXT_47': 'History',
	'TEXT_48': 'of the games',
	'TEXT_49': 'Prize sent',
	'TEXT_49_1': 'Error sending',
	'TEXT_50': 'Посмотреть полную историю игры',
	'TEXT_51': 'Winner',
	'TEXT_52': 'Amount of jackpot',
	'TEXT_53': '- how it works?',
	'TEXT_54': 'For each contributed $ 0.01',
	'TEXT_54_1':'(1 cent)', 
	'TEXT_54_2':'you get 1 ticket.',
	'TEXT_54_3':' copeks). ', 
	'TEXT_54_4':'For convenience, we show prices in rubles at the Central Bank. Meaning, for example, if you have made a deposit of rubles, you get 100 tickets ', 
	'TEXT_54_5':'(so',
	'TEXT_54_6': 'rubles = $ 1, $ 1 = 100 cents, 1 cent = 1 ticket)',
	'TEXT_55': 'At the beginning of each round , our system takes a completely randomly long integer from 0 to 1',
	'TEXT_55_1': '(for example',
	'TEXT_55_2': 'and encrypts it through md5, and displays it in encrypted form in the early rounds .',
	'TEXT_55_3': '(if you I do not know what the md5 - you can read the article on Wikipedia )',
	'TEXT_56': 'Then, when the round is over, the system shows the number , which was encrypted properly first ',
	'TEXT_57': '(you can check it on the website)' ,
	'TEXT_56_1': 'and multiply it by the Bank',
	'TEXT_56_2': '(in cents)',
	'TEXT_58': 'EXAMPLE',
	'TEXT_58_0': 'At the end of the round in the bank amounted to $ 1000',
	'TEXT_58_1': '(as we show prices in rubles, You will need to divide the bank at the rate',
	'TEXT_58_2': 'rub.) ',
	'TEXT_58_2_1': ' rub. ',
	'TEXT_58_3': 'and $ 1000$ = 100000 cents ',
	'TEXT_58_4': ' (1$ = 100 cents)',
	'TEXT_58_5': ' you will need to multiply by the number of 0.83952926436439157 Bank 100,000 cents ',
	'TEXT_58_6': '(this figures that we have taken as an example)',
	'TEXT_58_7': '  and obtain the number , which has 83 952 ticket.',
	'TEXT_58_8': 'Therefore, the sum of a large deposit you make - the more tickets you get and therefore better chance to get the winning ticket.',
	'TEXT_58_9': 'That is all. The principle of fair play is that we can not know what will be the bank at the end of the game, and randomly number to multiply by the bank we give at the beginning of the round and therefore even if we strongly wanted this , it would never have been able to do frontman winner.',

	'TEXT_59': 'Следовательно, чем на большую сумму депозит вы внесете - тем больше билетов вы получите, а значит выше шанс получить выигрышный билет',
	'TEXT_60': 'Принцип работы честной игры заключается в том, что мы никак не можем знать какой будет банк в конце игры, а рандомное число для умножения на банк мы даем в самом начале раунда и следовательно даже если бы мы сильно этого захотели, то никак бы не смогли сделать подставного победителя.',
	'TEXT_61': 'Checking fair play',
	'TEXT_62': 'Число раунда * банк (в копейках) / 64 (курс $) = выигрышный билет',
	'TEXT_63': 'Введите корректный хэш!',
	'TEXT_64': 'Введите корректное число раунда!',
	'TEXT_65': 'Enter the bank rounds (in cents)!',
	'TEXT_66': 'Hash Round and Round number do not match!',
	'TEXT_67': 'Выигрышный билет',
	'TEXT_68': 'My',
	'TEXT_69': 'history',
	'TEXT_70': 'Winning',
	'TEXT_71': 'Losing',
	'TEXT_72': 'chance',
	'TEXT_73': 'You contribute',
	'TEXT_74': ' which cost',
	'TEXT_75': 'Your win rate',
	'TEXT_76': 'Amount of jackpot',
	'TEXT_77': 'The cost of my inventory',
	
	'TEXT_81': 'My',
	'TEXT_82': 'profile',
	'TEXT_83': 'Nick',
	'TEXT_84': 'Games',
	'TEXT_85': 'Winning',
	'TEXT_86': 'Amount of banks',
	'TEXT_87': 'TOP-20',
	'TEXT_88': 'WINNERS',
	'TEXT_89': 'Profile',
	'TEXT_90': 'Participate',
	'TEXT_91': 'Sending win',
	'TEXT_92': 'Send an error',
	'TEXT_93': 'is hidden',
	'TEXT_94':'Jack-sweat',
	'Offer declined. No tradelink.': 'Offer declined. No tradelink.',
	'Offer declined because of pause': 'Offer declined because of pause',
	'Offer declined.': 'Offer declined.',
	'Offer declined. No items to receive.': 'Offer declined. No items to receive.',
	'Offer decline. You can bet only CSGO items.': 'Offer decline. You can bet only CSGO items.',
	'Offer declined: one user items limit exceeded.': 'Offer declined: one user items limit exceeded.',
	'Offer declined. Steam problems.': 'Offer declined. Steam problems.',
	'Offer declined. Steam error.': 'Offer declined. Steam error.',
	'Offer declined. Lower than min deposite.': 'Offer declined. Lower than min deposite.',
	'ABOUT': 'About',
	'SITE': 'the site',
	'INVENTORY': 'Inventory',
	'TITLE': 'Jackpot lottery CSGO.IN - The most honest CS: GO Roulette!',
	'WEBSITE_STATISTICS': 'website statistics',
	'TODAYS_WIN' : 'jackpot today',
	'BOT_STOP': 'Bot suspended.',
	'NAME': 'Name',
	'EXPERIENCE_YOUR_CHANCE': 'TEST YOUR CHANCE',
	'JOIN_GAME': 'Join the game',
	'JOIN_THE_GAME': 'Join the game',
	'ABSENT': 'is absent',
	'NEEDED': 'To start needed',
	'FINISH': 'GAME OVER',
	'OVER': 'The game is coming finish',
	'LATEST_RATES': 'latest rates taken from the queue in the current game',
	'TICKET' : 'Ticket',
	'HASH_ROUND': 'Xash round',
	'ITEM': 'item',
	'ITEM2': 'items',
	'PLAYER': 'player',
	'PLAYER2': 'players',
	'PLAYERS': 'players',
	'VIEW_FULL': '(watch full version of game)',
	'DURING': 'During sending',
	'TOP' : 'Top',
	'GAMERS' : '-players',
	'INVITERS' : ' inviters',
	'CHACKING': 'The number of rounds * Bank',
	'COPECKS': '(in cents)',
	'VALID': 'Please enter a valid hash!',
	'ROUND_VALID': 'Enter the correct number of rounds!',
	'SUM': 'Quantity cents in the round',
	'CHECK': 'Check',
	'WINNING_TIC': 'Winning ticket',
	'ALL': 'in all',
	'BACK_GO': 'back to main page',
	'SKIN': 'skin',
	'SKINS': 'skins',
	'SKINS2': 'skins',
	'SUPPORT_PEG': 'HUGE REQUEST BEFORE ASKING A QUESTION TO OUR TECH. SUPPORT TO READ THIS FAQ, WHERE YOU WILL FIND LIKELY TO ANSWER YOUR QUESTIONS.',
	'QUESTION': 'Question',
	'NOT_GET_ALL': 'I do not get all of the items after my victory!' ,
	'ANSWER': 'Answer',
	'COMMISSION': 'We take a commission 7% for every victory.',
	'WHAT_DO_I_DO': 'I won a pot and I didnt get my winnings, what do I do?',
	'ANSWER_SUPPORT': 'Sending items may take up about 30 minutes ( it depending on bots workload) and pay attention to Your inventory should be open in the privacy settings of your account Steam',
	'ITEM_DO_NOT': 'My item does not accepte, what do I do?' ,
	'LOADED': 'All coming items counted. If you can not see item, do not worry. We just could not download the information and picture from Steam. But the price of items is  loaded from Steam always and item is involved  with equal rights in the game.',
	'REJECT': 'Your bot rejects my trade!',
	'DETERMINE': 'because we can not determine the price of your items',
	'ALSO': 'And also items are accepted only for',
	'IF_YOU': 'If you put the items in trade from another game, such trade will also be rejected by our bot.',
	'IF_YOU2': 'If you do not find the answer to your question then you can ask it to our support service through this form to send messages to VK.',
	'SENDING_MES': ' SEND MESSAGE A SUPPORT IN VK',
	
	// TOP
	'TOP_ALL_THE_TIME' : 'All the time',
	'TOP_DAILY' : 'Today',
	'TOP_YESTERDAY' : 'Yesterday',
	'TOP_WEEKLY' : 'This week',
	'TOP_MONTHLY' : 'This month',

	// MAKE DEPOSIT
	'VIA_THE_SITE' : 'via the site',
	'VIA_THE_CLIENT' : 'via the client', 
	'THIS_METHOD_USED' : 'This method used by default. You make deposit through the site', 
	'IN_YOUR_BROWSER' : 'in your browser.', 
	'YOU_WILL_BE_MOVED' : 'You will be moved to the page for exchange with our bot.',
	'MAKE_DEPOSIT' : 'Make deposit', 
	'THIS_METHOD_PROVIDE' : 'This method provide for players who at first enter via browser. Deposit is made via Steam client.',
	'TO_MAKE_DEPOSIT' : 'To make deposit click the link which is under our bot nick.',

	// balance in profile & popup
	'BALANCE' : 'Balance',
	'BALANCE_DEPOSIT' : 'Add funds',
	'BALANCE_POPUP_TITLE' : 'Replenish balance',
	'BALANCE_POPUP_AMOUNT' : 'Enter amount',
	'BALANCE_POPUP_MAKE' : 'Make',
	'BALANCE_NOW' : 'Current balance',
	'BALANCE_PAYMENT_SYSTEM_TITLE' : 'Using payment system',
	'BALANCE_PAYMENT_SYSTEM_DESCR' : 'Pay any amount via one of the dozens of payment systems',
	'BALANCE_INVITES_TITLE' : 'Affiliate program',
	'BALANCE_INVITES_DESCR' : 'Earn money by inviting new players in the project using your referral link',
	'BALANCE_INVITES_BTN' : 'More',
	'BALANCE_SKINS_TITLE' : 'Fill up with skins',
	'BALANCE_SKINS_DESCR' : 'Give skins, get money on the balance.',
	'BALANCE_SKINS_BTN' : 'Send items',
	
	
	// chat
	'CHAT_ERROR_FLOOD' : 'Error! You can send not more then 3 messages in a row!',
	'MESSAGE' : 'Message',
	'SEND' : 'Send',
	'CHAT_TITLE' : 'Chat',
	'CHAT_LOGIN' : 'Login',
	'CHAT_ERROR_MUTED' : 'Your banned in chat till ',

	// cards
	'CARDS_DESCRIPTION' : 'You can bet a card instead of skins',
	'CARDS_ERROR_PAUSE' : 'Game is paused',

	// errors
	'ERROR_SET_TRADELINK' : 'Set your trade-link',
	'ERROR_LOW_BALANCE' : 'Low balance',
	'ERROR_LOW_BALANCE_DEPOSIT' : 'Low balance. Refill through a convenient way',
	'ERROR_BAD_REQUEST' : 'Error! Please try again later',

	'FEATURE_DISABLED_CARDS' : 'Feature is temporary disabled.',

	// @todo add prefix
	'SLOTS' : 'Slots ',
	'5_SEC' : 'Just 5 seconds and you have a full ',
	'USER' : 'user ',
	'PLACEHOLDER':'Enter your trade-offer link...', 

	// invites
	'INVITES_COUNT' : 'Invited',
	'INVITES_TOTAL' : 'Earn',
	'MENU_INVITES' : 'Invites',
	'INVITE_SYSTEM' : 'Referal program',
	'INVITE_SYSTEM_DESCR_1' : 'Send this link to your friend.',
	'INVITE_SYSTEM_DESCR_2' : 'Friend log in via Steam and make the first bid',
	'INVITE_SYSTEM_DESCR_3' : 'You and your friend get 15 rubles bonus!',

	// my inventory
	'MY_INVENTORY_TOTAL' : 'Total price',
	'MY_INVENTORY_TITLE': 'Title',
	'MY_INVENTORY_TYPE': 'Type',
	'MY_INVENTORY_PRICE': 'Price',
	'MY_INVENTORY_ERROR': 'Error loading equipment',

	//  trade-link
	'TRADE_LINK_TITLE': 'Enter',
	'TRADE_LINK_FORM': 'To start the game enter',
	'TRADE_LINK_BUTTON': 'Enter',
	'TRADE_OFFER_LINK_ITEM': 'Where does get it?',

	//  auth
	'AUTH_TITLE': 'Log in now',
	'AUTH_TITLE_MIN': 'and get 20 rubles as a bonus',
	'AUTH_USER_ENTER': 'spend 2 seconds and you can',
	'AUTH_ADVANTEGES_PLAY': 'Play in Jackpot lottery and other games', 
	'AUTH_ADVANTEGES_CHAT': 'Communicate in chat',
	'AUTH_ADVANTEGES_INVETE': 'Invite your friends and get bonuses',
	'AUTH_ADVANTEGES_SALE': 'Take part in a free lotteries',  
	'TOTAL_BET' : 'Total bet',
	'BET': 'Bet'
  });
 
  $translateProvider.translations('ru', {
	'LOGO' : '/img/logo.png',
	'MENU_MAIN': 'Главная',
	'MENU_PLAY': 'Играть',
	'MENU_ABOUT': 'О сайте',
	'MENU_TOP': 'ТОП игроков',
	'MENU_HISTORY': 'История',
	'MENU_INVENTORY': 'Инвентарь',
	'MENU_PROFILE': 'Профиль',
	'MENU_SUPPORT': 'поддержка',
	'MENU_LOGOUT': 'Выход',
	'LOGIN_VIA_STEAM' : 'Войти через Steam',
	'FOOTER_POWERED' : 'Powered by Steam, a registered trademark of Valve Corporation.',
	'SIDEBAR_ADD_TO_NICK_TITLE' : 'к нику csgo.in и получи  <span>+5%</span> к выигрышу',
	'SIDEBAR_ADD_TO_NICK_DESCR' : 'После смены ника, для вступления бонуса в силу, нажмите кнопку Выйти и зайдите на сайт заново.',
	'SIDEBAR_LAST_WINNER' : 'Последний победитель',
	'SIDEBAR_LAST_WINNER_MONEY' : 'Выигрыш:',
	'SIDEBAR_LAST_WINNER_CHANCE' : 'C шансом:',
	'SIDEBAR_ONLINE' : 'Сейчас онлайн',
	'SIDEBAR_PRICES' : 'Цены представлены:',
	'MAIN_JACKPOT_TITLE' : 'ГЛАВНЫЙ ДЖЕКПОТ ИГРЫ:',
	'MAIN_JACKPOT_DESCR' : 'Участники вносят ставки, по достижении определенного количества предметов случайным образом выбирается победитель, который получит все скины. Шанс выигрыша зависит от стоимости внесенных скинов.',
	'MAIN_INFORMERS_GAMES_TODAY' : 'Сегодня игр',
	'MAIN_INFORMERS_PLAYERS_TODAY' : 'Сегодня уникальных игроков',
	'MAIN_INFORMERS_ITEMS_TODAY' : 'Сегодня розыграно вещей',
	'MAIN_INFORMERS_MAX_JACKPOT' : 'Максимальный выигрыш',
	'MAIN_BANNER_TITLE' : 'Прими участие в розыграше!<br>Заходи в группу ВК и забери свой нож!',
	'MAIN_BANNER_BUTTON' : 'Получить нож',
	'GAME_NUMBER' : 'Игра',
	'SOUND_ON' : 'Включить звук',
	'SOUND_OFF' : 'Выключить звук',
	'BEFORE_TIMER_TEXT' : 'до начала розыгрыша',
	'ITEMS' : 'предметов',
	'OR_AFTER' : 'или через',
	'ENTER_GAME_AND_WIN' : 'Вступай в игру сейчас и выиграй',
	'YOU_BET' : 'Вы вложили в игру',
	'MIN_DEPOSITE' : 'Мин.ставка',
	'MAX_ITEMS' : 'максимум предметов',
	'GAME_ADDITIONAL_TEXT' : 'Чем выше ставка, тем больше шанс победить.',
	'MORE' : 'Подробнее',
	'YOUR_CHANCE' : 'Ваш шанс',
	'GAME_STARTED_FIRST' : 'Игра началась! Внеси ставку первым!',
	'GAME_STARTED' : 'Игра началась! Вносите ставки!',  
	'TOP_GAMERS' : 'ТОП ИГРОКОВ',
	'GAMERS_IN_RAITING' : 'Игроков <br>в рейтинге',
	'MAX_TODAY_WIN' : 'Максимальный <br>выигрыш сегодня',
	'TOP_PLACE' : 'Место',
	'TOP_RANK'  : 'Звание',
	'STEAM_NICK' : 'Ник в Steam',
	'WIN_COUNT' : 'Количество побед',
	'WON' : 'Выиграл',
	'ALL_GAMES' : 'ВСЕ ИГРЫ',
	'CHANCE' : 'Шанс',
	'IN_GAME' : 'НА КОНУ',
	'ENTER_AND_PLAY' : 'Войти и играть',
	'PLAYER_WON' : 'Победил игрок',
	'FROM' : 'из',
	'CHOOSE_GAME' : 'Выберите игру',
	'ENTER_LINK' : 'Внимание! Необходимо ввести ссылку на обмен. ',
	'WHERE_LINK' : 'Где взять ссылку?',
	'FOR_EXAMPLE' : 'Например',
	'SAVE_LINK' : 'Сохранить ссылку',
	'FOR_SURE' : 'Обязательно',
	'OPEN_INVENTORY' : 'откройте инвентарь',
	'TO_TAKE_PRIZE' : 'в Steam для получения приза!',
	'ADD_MORE_ITEMS' : 'Вложить еще',
	'END_GAME' : 'Игра окончена! Вносятся последние ставки',
	'PUTTED' : 'вложил',
	'END_GAME_STATUS' : 'Игра завершена!',
	'ENTER_TRADELINK' : 'Введите трейд-оффер ссылку',
	'ONLINE' : 'онлайн',
	'TODAY_GAMES' : 'игр сегодня',
	'TODAY_GAMERS' : 'игроков сегодня',
	'MAXIMUM_JACKPOT' : 'максимальный выигрыш',
	'TODAYS_WON' : 'сегодня выиграли',
	'SHOW_MAIN_BANNER' : 'display:block;',
	'GAME' : 'ИГРА',
	'BANK' : 'БАНК',
	'GAME_START' : 'Начало игры',
	'TICKETS' : 'Билеты',
	'FROMTO' : 'от',
	'TO' : 'до',
	'HASH' : 'хэш',
	'ROUND' : 'раунд',
	'MAIN_MENU_SUPPORT': 'Тех. поддержка',
	'TODAY_WIN': 'сегодня выиграли',
	'OR_TEXT': 'или через',
	'YOUR_BANK': 'Вы вложили в игру',
	'OF': 'из',
	'YOUR_CHANCE_2': 'Ваш шанс на победу',
	'ADD_ITEMS': 'Внести предметы',
	'ADD': 'Добавь',
	'ADD_CSGOIN': 'к нику csgo.in и получи +5% к выигрышу',
	'TAKE': 'Уважаемые победители! Во избежании проблем, просим',
	'MAX':'ВСЕ',
	'TAKE_0': 'сразу',
	'TAKE_0_1': 'ПРИНИМАТЬ',
	'TEXT_0': ' Ваш выигрыш!',
	'TEXT_1': 'ВНИМАНИЕ! Минимальная сумма депозита',
	'TEXT_2': 'Максимальный депозит -',
	'TEXT_3': 'предметов. Для старта необходимо 2 игрока.',
	'TEXT_4': 'Игра завершена! Вносятся последние депозиты.',	
	'TEXT_5': 'Честная игра',													
	'TEXT_6': 'Число раунда:',
	'TEXT_7': 'Выигрышный билет:',
	'TEXT_7_1': 'выигрышный билет:',
	'TEXT_8': 'внес',
	'TEXT_9': 'предметов',
	'TEXT_10': 'Игра началась! Вносите депозиты!',
	'TEXT_12': 'Хэш раунда:',
	'TEXT_13': ' – Сервис в котором участвующие вносят свои предметы (скины) и когда в сумме набирается 100 предметов, или истекает время, система определяет 1 победителя, которому и достаются все внесенные предметы.',
	'TEXT_14': 'Победитель определяется случайным образом, шанс выигрыша зависит от стоимости внесенных скинов.',
	'TEXT_15': 'ПРИНЦИП ПРОСТ',
	'TEXT_16': 'Чем больше и дороже предметы Вы ставите, тем больше шанс сорвать',
	'TEXT_17': 'джекпот! Но даже вкладывая 1 копейку, у Вас есть возможность сорвать джекпот!',
	'TEXT_18': 'КАК ЭТО РАБОТАЕТ',
	'TEXT_19': 'Вы вносите свои предметы через кнопку «Принять участие», отправляя трейд нашему боту.',
	'TEXT_20': 'Вы можете внести максимум 16 скинов за раз, общая сумма которых не может быть меньше 30₽',
	'TEXT_21': 'Мы переводим внесенные вами предметы в поинты в соотвествии с их ценой.',
	'TEXT_22': 'За каждый 1 цент стоимости предметы вы получити 1 поинт (1руб. - 100 поинтов). Шанс на победу зависит от количества поинтов. Чем больше предметов вы внесете – тем выше ваш шанс на победу.',
	'TEXT_23': 'При достижении порога в 100 скинов, или по истечению времени, мы собираем все выданные поинты вместе и случайным образом выбираем одного победителя.',
	'TEXT_24': 'При этом в приоритете те участники, у которых поинтов больше чем у остальных.',
	'TEXT_25': 'Победитель получает все внесенные предметы с учетом коммисии по окончанию раунда.',
	'TEXT_26': 'ПРАВИЛА И ОСОБЕННОСТИ:',
	'TEXT_27': 'Максимальный депозит предметов - 16 штук за трейд. Нет никаких верхних ограничений цены за предмет, депозит может начинаться общей суммой предметов не менее 30₽.',
	'TEXT_28': 'Если любой предмет ввести в “банк” на последний депозит и счётчик предметов переходит определенный порог, то они будут рассматриваться в рамках нынешнего раунда, поскольку пользователь внёс их на участие в текущем, а не в предыдущем раунде.',
	'TEXT_29': 'Для развития сайта и проведения конкурсов, мы взимаем комиссию с каждой игры - 10% от всех вещей игры.',
	'TEXT_30': 'Депозиты и вывод призового фонда происходят почти мгновенно. Принятие в течении 7 секунд. Вывод моментально.',
	'TEXT_31': 'Каждый раз отправляя предметы, Вы соглашаетесь с правилами использования сайта.',
	'TEXT_32': 'Если Ваш инвентарь закрыт, то следующая и последняя попытка отправки приза будет через 1 час. Повторная отправка приза выполняется уже тех. поддержкой.',
	'TEXT_33': 'Принимаются вещи только для CSGO, другие вещи будут приняты, но не будут засчитаны на сайте. Так-же мы можем гарантировать правильную оценку стоимости вещи только тогда, когда она есть на Торговой площадке Steam, или она не имеет сногсшибательную (выше в десятки раз) последнюю продажу, иначе ваш предмет может быть неверно оценен.',
	'TEXT_34': 'Запрещено ставить сувенирные предметы и сувенирные наборы, такие трейды отменяются.',
	'TEXT_34_1': 'И принимаются только те предметы, которые есть на ',
	'TEXT_34_2': 'торговой площадке Steam',
	'TEXT_35': 'Вы имеете гарантию получения ваших вещей до 23:00 этого же календарного дня. По истечении этого времени мы не несем ответственности за утерянные вещи.',
	'TEXT_36': 'Если вы отменили обмен или отправили контр-предложение после победы, то ваши вещи возвращены вам не будут, так как бот не рассчитан на повторную отправку вещей.',
	'TEXT_37': 'Если нашего бота забанили в течении 30 минут с окончания матча, мы возмещаем только вашу ставку, не выигрыш.',
	'TEXT_38': 'Если вы ставите в течении 30 секунд до окончания матча, то есть возможность что ваши скины попадут на следующую игру. Мы не несем за это ответственность: стим не всегда обрабатывает обмены мгновенно',
	'TEXT_39': 'Если по каким-то причинам игра была сорвана (Steam отключился), или вовсе не стоялась, мы возвращаем только Ваш депозит, через тех. поддержку.',
	'TEXT_40': 'ИГРА ЗАВЕРШЕНА',
	'TEXT_41': 'ВЕРНУТЬСЯ НА ГЛАВНУЮ',
	'TEXT_43': '(число раунда)',
	'TEXT_44': '(банк в копейках)',
	'TEXT_45': '(курс $)',
	'TEXT_46': '(победный билет)',
	'TEXT_47': 'История',
	'TEXT_48': 'игр',
	'TEXT_49': 'Выигрыш отправлен',
	'TEXT_49_1': 'Ошибка отправки',
	'TEXT_50': 'Посмотреть полную историю игры',
	'TEXT_51': 'Победитель',
	'TEXT_52': 'Сумма джекпота',
	'TEXT_53': '- как это работает?',
	'TEXT_54': 'За каждый внесенный 0,01$',
	'TEXT_54_1':'(1 цент)', 
	'TEXT_54_2':'вы получаете 1 билет.',
	'TEXT_54_3':' копейки). ', 
	'TEXT_54_4':'Для удобства мы выводим цены в рублях по курсу ЦБ. То есть, например, если вы внесли депозит на руб, то выполучите 100 билетов ', 
	'TEXT_54_5':'(т.к.',
	'TEXT_54_6': 'руб = 1$, 1$ = 100 центов, а 1 цент = 1 билет)',
	'TEXT_55': 'В начале каждого раунда наша система берет абсолютно рандомное длинное число от 0 до 1',
	'TEXT_55_1': '(например',
	'TEXT_55_2': 'и шифрует его через md5 , и показывает его в зашифрованом виде в начале раунда.',
	'TEXT_55_3': '(если вы не знаете, что такое md5 - можете почитать статью на википедии)',
	'TEXT_56': 'Затем, когда раунд завершился, система показывает то число, которое было шифровано вначале ',
	'TEXT_57': '(проверить его вы можете на сайте)' ,
	'TEXT_56_1': 'и умножает его на банк',
	'TEXT_56_2': '(в центах)',
	'TEXT_58': 'ПРИМЕР',
	'TEXT_58_0': 'В конце раунда банк составил 1000$ ',
	'TEXT_58_1': '(т.к. мы выводим цены в рублях, Вам нужно будет делить банк по курсу',
	'TEXT_58_2': ' руб.) ',
	'TEXT_58_2_1': ' руб. ',
	'TEXT_58_3': ' а 1000$ = 100000 центов ',
	'TEXT_58_4': ' (1$ = 100 центов) ',
	'TEXT_58_5': ' то нужно будет число 0.83952926436439157 умножить на банк 100000 центов ',
	'TEXT_58_6': ' (это цифры, которые мы брали для примера) ',
	'TEXT_58_7': 'и получим число, у которого есть 83952 билет.',
	'TEXT_58_8': 'Следовательно, чем на большую сумму депозит Вы внесете - тем больше билетов Вы получите, а значит выше шанс получить выигрышный билет.',
	'TEXT_58_9': 'Вот и всё. Принцип работы честной игры заключается в том, что мы никак не можем знать какой будет банк в конце игры, а рандомное число для умножения на банк мы даем в самом начале раунда и следовательно даже если бы мы сильно этого захотели, то никак бы не смогли сделать подставного победителя.',
	'TEXT_59': 'Следовательно, чем на большую сумму депозит вы внесете - тем больше билетов вы получите, а значит выше шанс получить выигрышный билет',
	'TEXT_60': 'Принцип работы честной игры заключается в том, что мы никак не можем знать какой будет банк в конце игры, а рандомное число для умножения на банк мы даем в самом начале раунда и следовательно даже если бы мы сильно этого захотели, то никак бы не смогли сделать подставного победителя.',
	'TEXT_61': 'Проверка честной игры',
	'TEXT_62': 'Число раунда * банк (в копейках) / 64 (курс $) = выигрышный билет',
	'TEXT_63': 'Введите корректный хэш!',
	'TEXT_64': 'Введите корректное число раунда!',
	'TEXT_65': 'Введите банк раунда (в копейках)!',
	'TEXT_66': 'Хэш Раунда и Число Раунда не совпадают!',
	'TEXT_67': 'Выигрышный билет',
	'TEXT_68': 'Моя',
	'TEXT_69': 'история',
	'TEXT_70': 'Выигрыш',
	'TEXT_71': 'Проигрыш',
	'TEXT_72': 'шанс',
	'TEXT_73': 'Вы внесли',
	'TEXT_74': ' на сумму',
	'TEXT_75': 'Ваш шанс на выигрыш',
	'TEXT_76': 'Сумма джек-пота',
	'TEXT_77': 'Стоимость моего инвентаря',
	'TEXT_81': 'Мой',
	'TEXT_82': 'профиль',
	'TEXT_83': 'Ник',
	'TEXT_84': 'Игр',
	'TEXT_85': 'Побед',
	'TEXT_86': 'Сумма банков',
	'TEXT_87': 'Топ-20',
	'TEXT_88': 'победителей',
	'TEXT_89': 'Профиль',
	'TEXT_90': 'Участий',
	'TEXT_91': 'Отправка выигрыша',
	'TEXT_92': 'Ошибка выигрыша',
	'TEXT_93': 'скрыто',
	'TEXT_94':'Джек-пот',
	'Offer declined. No tradelink.': 'Предложение отклонено. Укажите ваш трейд-линк!',
	'Offer declined because of pause': 'Предложение отклонено из-за паузы',
	'Offer declined.': 'Предложение отклонено.',
	'Offer declined. No items to receive.': 'Предложение отклонено. Нет предметов для получения ',
	'Offer decline. You can bet only CSGO items.': 'Предложение отклонено. Вы можете ставить только предметы CSGO',
	'Offer declined: one user items limit exceeded.': 'Предложение отклонено: превышен лимит предметов для одного пользователя',
	'Offer declined. Steam problems.': 'Предложение отклонено. Проблемы со Steam',
	'Offer declined. Steam error.': 'Предложение отклонено. Ошибка с Steam',
	'Offer declined. Lower than min deposite.': 'Предложение отклонено. Меньше минимального депозита',
	'(Minimal Wear)': '(Немного подношенное)',
	'(Well-Worn)': '(Сильно изношенное)',
	'(Field-Tested)': '(После полевых испытаний)',
	'(Factory New)': '(Прямо с завода)',
	'ABOUT': 'О',
	'SITE': 'сайте',
	'INVENTORY': 'Инвентарь',
	'TITLE': 'Джекпот-лотерея CSGO.IN – Самая честная CS:GO рулетка!',
	'WEBSITE_STATISTICS': 'Статистика сайта',
	'TODAYS_WIN' : 'выигрыш сегодня',
	'BOT_STOP': 'Бот приостановлен.',
	'NAME': 'Имя',
	'EXPERIENCE_YOUR_CHANCE': 'ИСПЫТАЙ СВОЙ ШАНС',
	'JOIN_GAME': 'Вступи в игру',
	'JOIN_THE_GAME': 'ВСТУПИТЬ В ИГРУ',
	'ABSENT': 'отсутствует',
	'NEEDED': 'Для старта необходимо ',
	'FINISH': 'ИГРА ЗАКОНЧИЛАСЬ',
	'OVER': 'ИГРА ЗАКАНЧИВАЕТСЯ',
	'LATEST_RATES': 'принимаются последние ставки из очереди в текущую игру',
	'TICKET': 'Билет',
	'HASH_ROUND': 'Хеш раунда',
	'ITEM': 'предмет',
	'ITEM2': 'предмета',
	'PLAYER': 'игрок',
	'PLAYER2': 'игрока',
	'PLAYERS': 'игроков',
	'VIEW_FULL': '(посмотреть полную версию игры)',
	'DURING': 'В процессе отправки',
	'TOP' : 'ТОП',
	'GAMERS' : '-игроков',
	'INVITERS' : 'рефоводов',
	'CHACKING': 'Число раунда* банк',
	'COPECKS': '(в копейках)',
	'VALID': 'Введите корректный хеш!',
	'ROUND_VALID': 'Введите корректное число раунда!',
	'SUM': 'Количество копеек в раунде',
	'CHECK': 'Проверить',
	'WINNING_TIC': 'Победный билет',
	'ALL': 'всего',
	'BACK_GO': 'Вернуться на главную страницу',
	'SKIN': 'скин',
	'SKINS': 'скина',
	'SKINS2': 'скинов',
	'SUPPORT_PEG': 'ОГРОМНАЯ ПРОСЬБА ПЕРЕД ТЕМ КАК ЗАДАВАТЬ ВОПРОС В НАШУ ТЕХ. ПОДДЕРЖКУ ПРОЧИТАЙТЕ ДАННЫЙ FAQ, ГДЕ ВЫ ВЕРОЯТНЕЕ ВСЕГО НАЙДЕТЕ ОТВЕТ НА ВАШИ ВОПРОСЫ.',
	'QUESTION': 'Вопрос',
	'NOT_GET_ALL': 'Мне пришли не все предметы после победы!' ,
	'ANSWER': 'Ответ',
	'COMMISSION': 'C каждой победы мы берем комиссию 7%.',
	'WHAT_DO_I_DO': 'Мне не пришел выигрыш!',
	'ANSWER_SUPPORT': 'Отправка предметов может занимать до 30 минут (в зависимости от загруженности ботов), а также обратите внимание на то, что в настройках приватности вашего аккаунта Steam Ваш инвентарь должен быть открыт',
	'ITEM_DO_NOT': 'Моя вещь не засчиталась, что делать?',
	'LOADED': 'Все пришедшие вещи засчитываются. Если вещь не отображается, не стоит волноваться. Мы просто не смогли загрузить из Стима информацию и картинку. Но цена вещи из Стима всегда загружается и вещь участвует на равных правах в играх.',
	'REJECT': 'Ваш бот отклоняет мой трейд!',
	'ALSO': 'А также принимается вещи только для',
	'DETERMINE': 'т.к. мы не сможем определить цену Вашего предмета',
	'IF_YOU': 'Если Вы положили в трейд предметы с другой игры, такой трейд тоже будет отклонен нашим ботом.',
	'IF_YOU2': 'Если Вы здесь не нашли ответа на Ваш вопрос, тогда Вы можете задать его нашему саппорту через эту форму отправки сообщений в VK.',
	'SENDING_MES': ' Отправить сообщение саппорту в ВК',
	
	// TOP
	'TOP_ALL_THE_TIME' : 'За все время',
	'TOP_DAILY' : 'За сегодня',
	'TOP_YESTERDAY' : 'За вчера',
	'TOP_WEEKLY' : 'За неделю',
	'TOP_MONTHLY' : 'За месяц',

	// MAKE DEPOSIT
	'VIA_THE_SITE' : 'через сайт',
	'VIA_THE_CLIENT' : 'через steam', 
	'THIS_METHOD_USED' : 'Этот способ используется по-умолчанию. Ставка будет принята через сайт', 
	'IN_YOUR_BROWSER' : 'в вашем браузере.', 
	'YOU_WILL_BE_MOVED' : 'Вы перейдете на страницу обмена с нашим ботом.',
	'MAKE_DEPOSIT' : 'Вступить в игру', 
	'THIS_METHOD_PROVIDE' : 'Этот способ нужен для игроков, которые впервые зашли на свой профиль через браузер, при этом часто пользуются приложением Steam',
	'TO_MAKE_DEPOSIT' : 'Чтобы сделать ставку, нажмите на ссылку под ником нашего бота.',

	// balance in profile & popup
	'BALANCE' : 'Баланс',
	'BALANCE_DEPOSIT' : 'Пополнить',
	'BALANCE_POPUP_TITLE' : 'Пополнение баланса',
	'BALANCE_POPUP_AMOUNT' : 'Введите сумму',
	'BALANCE_POPUP_MAKE' : 'Пополнить',
	'BALANCE_NOW' : 'Текущий баланс',
	'BALANCE_PAYMENT_SYSTEM_TITLE' : 'С помощью платежной системы',
	'BALANCE_PAYMENT_SYSTEM_DESCR' : 'Внесите любую сумму с помощью одной из десятков платежных систем',
	'BALANCE_INVITES_TITLE' : 'Партнерская программа',
	'BALANCE_INVITES_DESCR' : 'Получайте деньги за приглашение новых игроков на проект с помощью реферальной ссылки',
	'BALANCE_INVITES_BTN' : 'Подробнее',
	'BALANCE_SKINS_TITLE' : 'Пополнить скинами',
	'BALANCE_SKINS_DESCR' : 'Внесите скины, получите деньги на баланс.',
	'BALANCE_SKINS_BTN' : 'Внести предметы',

	// chat
	'MESSAGE' : 'Сообщение',
	'SEND' : 'Отправить',
	'CHAT_TITLE' : 'Чат',
	'CHAT_LOGIN' : 'Войти',
	'CHAT_ERROR_FLOOD' : 'Ошибка! Не более 3 сообщений подряд.',
	'CHAT_ERROR_MUTED' : 'Бан чата до ',

	// cards
	'CARDS_DESCRIPTION' : 'Вместо предметов вы можете вносить наши карточки',
	'CARDS_ERROR_PAUSE' : 'Игра на паузе',

	// errors
	'ERROR_SET_TRADELINK' : 'Введите трейд-оффер ссылку',
	'ERROR_LOW_BALANCE' : 'Недостаточно средств на счету',
	'ERROR_LOW_BALANCE_DEPOSIT' : 'Недостаточно средств на счету. Пополните удобным способом',
	'ERROR_BAD_REQUEST' : 'Произошла ошибка! Пожалуйста, попробуйте еще раз позднее',
	'FEATURE_DISABLED_CARDS' : 'Функция временно недоступна в связи с запуском магазина.',

	// @todo add prefix
	'SLOTS' : 'Слоты ',
	'5_SEC' : 'Всего 5 сек и ты полноправный ',
	'USER' : 'пользователь ',
	'PLACEHOLDER':'Введите ссылку...',

	// invites
	'INVITES_COUNT' : 'Пригласил',
	'INVITES_TOTAL' : 'Заработал',
	'MENU_INVITES' : 'Рефералка',
	'INVITE_SYSTEM' : 'Реферальная программа',
	'INVITE_SYSTEM_DESCR_1' : 'Отправляешь ссылку друзьям.',
	'INVITE_SYSTEM_DESCR_2' : 'Друг регистрируется и делает первую ставку.',
	'INVITE_SYSTEM_DESCR_3' : 'Ты и друг получаете по 15 рублей!',

	// my inventory
	'MY_INVENTORY_TOTAL' : 'Общая стоимость',
	'MY_INVENTORY_TITLE': 'Название',
	'MY_INVENTORY_TYPE': 'Тип',
	'MY_INVENTORY_PRICE': 'Цена',
	'MY_INVENTORY_ERROR': 'Ошибка при загрузке инвентаря',


	//  trade-link
	'TRADE_LINK_TITLE': 'Введите',
	'TRADE_LINK_FORM': 'Чтобы вступить в игру укажите',
	'TRADE_LINK_BUTTON': 'Ввести',
	'TRADE_OFFER_LINK_ITEM': 'Где его взять?',

	//  auth
	'AUTH_TITLE': 'Авторизируйся сегодня',
	'AUTH_TITLE_MIN': 'и получи 20 руб на бонус',
	'AUTH_USER_ENTER': 'потрать 2 секунды и ты сможешь',
	'AUTH_ADVANTEGES_PLAY': 'Играть в джекпот-лотерею и другие игры', 
	'AUTH_ADVANTEGES_CHAT': 'Общаться в чате',
	'AUTH_ADVANTEGES_INVETE': 'Приглашать друзей и зарабатывать бонусы',
	'AUTH_ADVANTEGES_SALE': 'Принимать участие в бесплатных розыгрышах',
	'TOTAL_BET' : 'Текущие ставки',
	'BET': "Поставить",


});
 
  $translateProvider.preferredLanguage('ru');
}]);